### ISSUE TITLE
怎么感觉有种py写成java的感觉

### ISSUE THREAD

**Issue by qq727127158** [mengzxh/weixin_friend_check#1]
试了下，的确达到了检测的目的。不过效率有待改进，能够加入其它资源的批量删除好友功能就比较完善了。

**Comment by mengzxh** [comment]
效率改进不了，因为调用的微信的接口，频率快了微信会提示发送消息失败的。删除功能暂时不会加的，这个还是用户自己来安全吧🐱

**Comment by qq727127158** [comment]
> 效率改进不了，因为调用的微信的接口，频率快了微信会提示发送消息失败的。删除功能暂时不会加的，这个还是用户自己来安全吧

现在不能用拉群检测了吗？

**Comment by mengzxh** [comment]
> > 效率改进不了，因为调用的微信的接口，频率快了微信会提示发送消息失败的。删除功能暂时不会加的，这个还是用户自己来安全吧
> 
> 现在不能用拉群检测了吗？

不行，微信网页版已经屏蔽了拉群的功能
